#!/usr/bin/env python2.7
# this script reads in EEG data generated by the MindWave
import numpy as np

# loads the raw data (stored in the third column of a CSV file)
def load_data(filename):
	data = np.genfromtxt(filename, delimiter = ',', usecols = (2), skip_header = 1)
	return data


#params
fiveSec = 2541
numFiles = 3
numClasses = 2
samplesPerClass = 6
frontCutOff = 300
endCutOff = 241
sample_len = fiveSec - frontCutOff - endCutOff
path = './'


splitData = np.zeros([numFiles * numClasses * samplesPerClass, sample_len])
splitLabels = np.zeros([numFiles * numClasses * samplesPerClass])

ind_ct = 0
for filenum in range(1,numFiles+1):
	filename = '{}beachandstorm{}.csv'.format(path, filenum)
	data = load_data(filename)
	lenData = data.shape[0]
	print lenData

	#place sample data in data array
	time_ct = 0
	for k in range(numClasses * samplesPerClass):
		print filenum, time_ct, ind_ct
		splitData[ind_ct] = data[time_ct + frontCutOff : time_ct + fiveSec - endCutOff]
		splitLabels[ind_ct] = ind_ct % 2
		ind_ct += 1
		time_ct += fiveSec


print(splitData.shape)
print(splitLabels)

SaveDir = './'
np.save('{}split_data'.format(SaveDir), splitData)
np.save('{}split_labels'.format(SaveDir) , splitLabels)
