# This script reads in EEG data generated by the MindWave

import numpy as np


#loads the raw data (stored in the third column of a csv file)
def load_data(filename):
	data = np.genfromtxt(filename, delimiter=',', usecols=(2), skip_header=1)
	return data

path = '/Users/johnmcguinness/Downloads/'
filename = '{}eegIDRecord.csv'.format(path)

data = load_data(filename)

print data.shape
