#!/usr/bin/env python2.7
# this script reads in EEG data generated by the MindWave
import numpy as np

# loads the raw data (stored in the third column of a CSV file)
def load_data(filename):
	data = np.genfromtxt(filename, delimiter = ',', usecols = (2), skip_header = 1)
	return data

path = '/Users/Sophie/Desktop/School Stuff/Budapest/Code/EEG/'
filename = '{}eegIDRecord.csv'.format(path)

data = load_data(filename)
print data.shape

lenData = data.shape[0]
fiveSec = 2572
numClasses = 2
samplesPerClass = 3
frontCutOff = 272
endCutOff = 300

splitData = np.zeros([numClasses * samplesPerClass, fiveSec - 572])
splitLabels = np.zeros([numClasses * samplesPerClass])

count = 0

for i in range(0, lenData, fiveSec):
	splitData[count] = data[i + frontCutOff : i + fiveSec - endCutOff]
	splitLabels[count] = count % 2
	count += 1

print(splitData.shape)
print(splitLabels)

np.save('split_data', splitData)
np.save('split_labels', splitLabels)
